pipeline:
  identifier: Build_harness_demo_python_1692180118772
  name: Build harness-demo-python
  orgIdentifier: default
  projectIdentifier: HarnessLearning
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1692180082544
        repoName: zenki209/harness-demo-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
